### ISSUE TITLE
nerf_quick_start에서 Step3 Run NeRF 실행을 하는 경우 설치 및 실행 오류가 발생함

### ISSUE THREAD

**Issue by Songinpyo** [ProtossDragoon/PlankHyundong#23]
### 문제상황

Step3 Run NeRF 이전 까지는 눈에 띄는 로그는 없는데 Step3부터 오류 메세지가 생기고 실행이 잘 안되고 있습니다.

### 스크린샷 등 시각자료
1. 설치 에러 메세지
![image](https://user-images.githubusercontent.com/104220612/204120085-a86c6a87-4f4a-477b-8b8a-13fae9dd9d11.png)

2. 설치 에러 때문에 실행이 제대로 안되는 것으로 예상
![image](https://user-images.githubusercontent.com/104220612/204120120-0f57d496-cd5b-4d1b-9c1c-2e982d20a069.png)

**Comment by yyongjae** [comment]
안녕하세요! 계속 문제가 발생해서 죄송합니다. 확인해보고 수정하겠습니다!

**Comment by Sumyeong-Jang** [comment]
안녕하세요 인표님, 말씀해주신대로 해당 이슈는 의존 패키지를 설치하는 과정에서의 오류로 인해 실행에 문제가 있었습니다. [Index of /ubuntu/pool/main/i/imagemagick](http://security.ubuntu.com/ubuntu/pool/main/i/imagemagick/) 에서 확인되는 것과 같이 최근 2022-11-25에 업데이트 된 imagemagick 패키지의 버전 문제로 보입니다.

이슈가 발생한 바로 상단 코드 셀에서 `!apt-get update`로 업데이트 후 실행하시면 빠른 해결이 가능합니다.
이전과 마찬가지로 버전 문제가 계속 발생하여 사용에 불편을 드린 점 죄송합니다. 이 부분에 대해 확인 후 노트북과 이슈를 업데이트 해드리겠습니다.

**Comment by yyongjae** [comment]
#24
