### ISSUE TITLE
hyundong360 데이터셋에 대해 LLFF 를 적용할 때 에러가 발생함

### ISSUE THREAD

**Issue by ProtossDragoon** [ProtossDragoon/PlankHyundong#3]
### 문제상황

- hyundong360 데이터셋에 대해 LLFF 를 적용할 때 에러가 발생함

### 참고자료

- [관련 노션 칸반](https://www.notion.so/janghoo/360-360-NeRF-3D-d70d19c4f45b410da77337e6219587de)
- [에러 소스코드, colmap-colab.ipynb](https://github.com/ProtossDragoon/PlankHyundong/blob/main/notebooks/colmap_colab.ipynb)
- [관련 데이터셋, hyundong360](https://drive.google.com/drive/folders/1EbId4u6S5Vtjgxr41yJqmAJj0L-FAeXj?usp=sharing)

### 스크린샷 등 시각자료

- https://github.com/ProtossDragoon/PlankHyundong/issues/2#issue-1295121537 스크린샷 참고

![image](https://user-images.githubusercontent.com/46595649/177473359-7a1e20d7-fc66-4556-beda-07a82662d5a8.png)

**Comment by ProtossDragoon** [comment]
[노션 칸반](https://www.notion.so/janghoo/hyundong360-69d4e1689a604cd4bed7d09b2216805a) 추가함

**Comment by yyongjae** [comment]
해결. 데이터 개수가 부족해서 생긴 문제라고 판단.
기존 40개 -> 200개로 늘리니 Colmap 실행 완료

**Comment by ProtossDragoon** [comment]
https://github.com/ProtossDragoon/PlankHyundong/commit/8aec9f5b66acbb3926964972050c993807b02c57 소스코드 이용
